### ISSUE TITLE
Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by cuongcx1998** [faceplugin/Face-Recognition-SDK-Javascript#2]
I detect liveness via webcam, when video running a time interval , i got error 
`abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2146959360, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")`
How to fix it? Thanks!!

**Comment by faceplugin** [comment]
Let me take a look this problem
