### ISSUE TITLE
Question about liveness detection

### ISSUE THREAD

**Issue by TuyenDang240598** [faceplugin/Face-Recognition-SDK-Javascript#5]
Hi, your project is so amazing. Especially, the liveness detection is very good.
Could I have some questions about your liveness detection model:

1.  Can you give me the paper that you implement to train the model or can you share with me the strategy?
2.  Which dataset was used in training?
3. There are 3 values at the output of model, the first value present for spoof or not spoof with threshold is 0.3. How about the 2 other meaning?

Hope to get your response soon.

**Comment by faceplugin** [comment]
Hello @TuyenDang240598 
First off, hopefully you're safe and doing well.

1. At this time, I don't have special paper for liveness detection. I'm using mobilenet based custom model.
2. For the training, there are some public and private dataset here.
3. Yes. In the output, there are 3 values. The first one is for real, 2nd for 2D spoof like presentation, 3nd for 3D spoof like silicone mask.

Cheers

**Comment by TuyenDang240598** [comment]
Thank you so much for your information.
